import { useState } from 'react';
import { useRemote,useAction } from '../../hooks/useRemote';
import { send } from '../../services/api';
import type { OrderDTO } from '../../services/orderService';
import { Panel,Card,RemoteState,Notice,Status,field,button,secondary,money } from '../../components/DataUI';
interface Dispute {id:string;orderId:string;buyerName:string;amount:number;description:string;status:string;evidenceUrl?:string;resolutionNote?:string;refundAmount?:number}
interface Message {id:number;author:string;content:string;createdAt:string}
function Chat({id}:{id:string}){const remote=useRemote<Message[]>(`/disputes/${id}/messages`);const action=useAction(remote.reload);const [content,setContent]=useState('');return <div className="border-t border-border pt-3 space-y-3"><RemoteState {...remote} empty={!remote.data?.length} retry={remote.reload}/>{remote.data?.map(m=><p key={m.id}><strong>{m.author}:</strong> {m.content}</p>)}<Notice error={action.error}/><form className="flex gap-2" onSubmit={async e=>{e.preventDefault();if(await action.run(()=>send(`/disputes/${id}/messages`,{content})))setContent('');}}><input aria-label="Nội dung phản hồi" className={field} required maxLength={4000} value={content} onChange={e=>setContent(e.target.value)}/><button className={button} disabled={action.busy}>Gửi</button></form></div>;}
export default function DisputePanel({admin=false}:{admin?:boolean}){
  const remote=useRemote<Dispute[]>(admin?'/admin/disputes':'/disputes');const orders=useRemote<OrderDTO[]>(admin?null:'/orders/me');const action=useAction(remote.reload);
  const [orderId,setOrder]=useState('');const [description,setDescription]=useState('');const [evidenceUrl,setEvidence]=useState('');const [chat,setChat]=useState('');
  return <Panel title={admin?'Xử lý tranh chấp':'Tranh chấp và phản hồi'}><Notice error={action.error}/>
    {!admin&&<Card><form className="space-y-3" onSubmit={async e=>{e.preventDefault();if(await action.run(()=>send('/disputes',{orderId,description,evidenceUrl}))){setDescription('');setEvidence('');}}}><label>Đơn hàng<select className={field} required value={orderId} onChange={e=>setOrder(e.target.value)}><option value="">Chọn đơn hàng</option>{orders.data?.map(o=><option key={o.id} value={o.id}>{o.id}</option>)}</select></label><Notice error={orders.error}/><label>Nội dung<textarea className={field} required value={description} onChange={e=>setDescription(e.target.value)}/></label><label>URL bằng chứng<input type="url" className={field} value={evidenceUrl} onChange={e=>setEvidence(e.target.value)}/></label><button className={button} disabled={action.busy}>Tạo tranh chấp</button></form></Card>}
    <RemoteState {...remote} empty={!remote.data?.length} retry={remote.reload}/>{remote.data?.map(d=><Card key={d.id}><p className="break-all">Đơn {d.orderId} · {d.buyerName}</p><Status value={d.status}/><p>{d.description}</p>{d.evidenceUrl&&<a href={d.evidenceUrl} target="_blank" rel="noreferrer" className="text-emerald-300">Bằng chứng</a>}{d.resolutionNote&&<p>Kết luận: {d.resolutionNote}</p>}{!!d.refundAmount&&<p>Quyết định hoàn: {money(d.refundAmount)}. Cần đối soát việc chuyển tiền.</p>}
      <div className="flex gap-2 flex-wrap"><button className={secondary} onClick={()=>setChat(chat===d.id?'':d.id)}>Xem phản hồi</button>
      {admin&&['OPEN','UNDER_REVIEW'].includes(d.status)&&['RESOLVED','REJECTED'].map(status=><button key={status} className={button} disabled={action.busy} onClick={()=>void action.run(async()=>{const resolutionNote=prompt('Nội dung kết luận:');if(!resolutionNote)return;const value=status==='RESOLVED'?prompt('Số tiền quyết định hoàn (0 nếu không hoàn):','0'):'0';if(value===null)return;const refundAmount=Number(value);if(!Number.isFinite(refundAmount)||refundAmount<0||refundAmount>d.amount)throw new Error('Số tiền hoàn không hợp lệ.');await send(`/admin/disputes/${d.id}/resolution`,{status,resolutionNote,refundAmount,refundType:refundAmount===d.amount?'FULL':'PARTIAL'},'put');})}>{status==='RESOLVED'?'Giải quyết':'Từ chối'}</button>)}</div>{chat===d.id&&<Chat id={d.id}/>}</Card>)}
  </Panel>;
}
